---
- name: "Build a container with ansible"
  hosts: localhost
  connection: local
  tasks:
    - name: stop current running container
      command: docker stop meeting
      ignore_errors: yes

    - name: remove stopped container
      command: docker rm meeting
      ignore_errors: yes

    - name: remove meeting_meet
      command: docker rmi meeting_meet
      ignore_errors: yes


    - name: build docker  using the Docker-compose
      command:  docker-compose build

    - name: tag Image to dockerhub
      command: docker tag sirinee/meeting meeting

    - name: Push Image to dockerhub
      command: docker push sirinee/meeting

    - name: run container
      command: docker-compose up
